When using the latest version of each dependency, the following errors occurred: Jinja2 			3.1.2 		AttributeError: module 'jinja2.ext' has no attribute 'with_' scikit-learn 	1.0.2		ModuleNotFoundError: No module named 'sklearn.metrics.scorer' 							ModuleNotFoundError: No module named 'sklearn.feature_selection.base'
The changes in 'html.py', 'permutation_importance.py' and 'transform.py' are such that these errors are resolved while maintaining support for older versions of jinja2 and scikit-learn.

'test_import.py' is used to test importing eli5 for both newer and older dependency versions.